#!/usr/bin/env bash
monitorConfigs=()
commands=()
mapfile -t xrandrLines < <( xrandr | grep -n "\bconnected\b" )
for index in $(seq ${#xrandrLines[@]}) ; do
    ## Gets line to get best config from
    index=$(( index -= 1 )) 
    if [[ ${xrandrLines[$index]:1:1} == *":"* ]] ; then
        line=${xrandrLines[$index]:0:1}
    else
        line=${xrandrLines[$index]:0:2}
    fi
    ## Get name of Monitor
    name=$(echo ${xrandrLines[$index]} | awk '{ print $1 }' | awk -F: '{ print $2 }')
    # Gets configs for monitor
    monitorConfigs[$index]=$(xrandr | head -n $(( line + 1 )) | tail -n 1)
    resolution=$(echo ${monitorConfigs[$index]} | awk '{ print $1 }')
    rate=$(echo ${monitorConfigs[$index]} | awk '{ print $3 }' | tr "*" " ")
    if [[ $rate == "+" ]] ; then
        rate=$(echo ${monitorConfigs[$index]} | awk '{ print $4 }' | tr "*" " ")
    fi
    echo "Name: $name"
    echo "Resolution: $resolution"
    echo "Refresh Rate: $rate"
    echo "-----"
    if [[ $index -eq 0 ]] ; then
        xrandr --output $name  --mode $resolution --rate $rate
    else
        xrandr --output $name --primary --mode $resolution --rate $rate --left-of $lastMonitorName
    fi
    lastMonitorName=$name
done

